/*********************                                                        */
/** options.h
 **
 ** Copyright 2011-2013  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     ../../../src/options/mkoptions ../../../src/options/base_options_template.h ../main/options.h
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.h
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2013  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include <cvc4/cvc4_public.h>

#ifndef __CVC4__OPTIONS__DRIVER_H
#define __CVC4__OPTIONS__DRIVER_H

#include <cvc4/options/options.h>

#line 30 "../../../src/options/../main/options"
#include <vector>
#line 30 "../../../src/options/../main/options"
#include <string>

#line 26 "../../../src/options/base_options_template.h"

#define CVC4_OPTIONS__DRIVER__FOR_OPTION_HOLDER \
  version__option_t::type version; \
  bool version__setByUser__; \
  help__option_t::type help; \
  bool help__setByUser__; \
  earlyExit__option_t::type earlyExit; \
  bool earlyExit__setByUser__; \
  threads__option_t::type threads; \
  bool threads__setByUser__; \
  threadArgv__option_t::type threadArgv; \
  bool threadArgv__setByUser__; \
  thread_id__option_t::type thread_id; \
  bool thread_id__setByUser__; \
  sharingFilterByLength__option_t::type sharingFilterByLength; \
  bool sharingFilterByLength__setByUser__; \
  fallbackSequential__option_t::type fallbackSequential; \
  bool fallbackSequential__setByUser__; \
  incrementalParallel__option_t::type incrementalParallel; \
  bool incrementalParallel__setByUser__; \
  segvSpin__option_t::type segvSpin; \
  bool segvSpin__setByUser__; \
  waitToJoin__option_t::type waitToJoin; \
  bool waitToJoin__setByUser__;

#line 30 "../../../src/options/base_options_template.h"

namespace CVC4 {

namespace options {


#line 8 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC version__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } version CVC4_PUBLIC;
#line 11 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC help__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } help CVC4_PUBLIC;
#line 22 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC earlyExit__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } earlyExit CVC4_PUBLIC;
#line 26 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC threads__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } threads CVC4_PUBLIC;
#line 30 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC threadArgv__option_t { typedef std::vector<std::string> type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } threadArgv CVC4_PUBLIC;
#line 32 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC thread_id__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } thread_id CVC4_PUBLIC;
#line 34 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC sharingFilterByLength__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } sharingFilterByLength CVC4_PUBLIC;
#line 36 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC fallbackSequential__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } fallbackSequential CVC4_PUBLIC;
#line 38 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC incrementalParallel__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } incrementalParallel CVC4_PUBLIC;
#line 41 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC segvSpin__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } segvSpin CVC4_PUBLIC;
#line 45 "../../../src/options/../main/options"
extern struct CVC4_PUBLIC waitToJoin__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } waitToJoin CVC4_PUBLIC;

#line 38 "../../../src/options/base_options_template.h"

}/* CVC4::options namespace */


#line 8 "../../../src/options/../main/options"
template <> const options::version__option_t::type& Options::operator[](options::version__option_t) const;
#line 8 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::version__option_t) const;
#line 8 "../../../src/options/../main/options"
template <> void Options::assignBool(options::version__option_t, std::string option, bool value, SmtEngine* smt);
#line 11 "../../../src/options/../main/options"
template <> const options::help__option_t::type& Options::operator[](options::help__option_t) const;
#line 11 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::help__option_t) const;
#line 11 "../../../src/options/../main/options"
template <> void Options::assignBool(options::help__option_t, std::string option, bool value, SmtEngine* smt);
#line 22 "../../../src/options/../main/options"
template <> const options::earlyExit__option_t::type& Options::operator[](options::earlyExit__option_t) const;
#line 22 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::earlyExit__option_t) const;
#line 22 "../../../src/options/../main/options"
template <> void Options::assignBool(options::earlyExit__option_t, std::string option, bool value, SmtEngine* smt);
#line 26 "../../../src/options/../main/options"
template <> const options::threads__option_t::type& Options::operator[](options::threads__option_t) const;
#line 26 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::threads__option_t) const;
#line 26 "../../../src/options/../main/options"
template <> void Options::assign(options::threads__option_t, std::string option, std::string value, SmtEngine* smt);
#line 30 "../../../src/options/../main/options"
template <> void Options::set(options::threadArgv__option_t, const options::threadArgv__option_t::type& x);
#line 30 "../../../src/options/../main/options"
template <> const options::threadArgv__option_t::type& Options::operator[](options::threadArgv__option_t) const;
#line 30 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::threadArgv__option_t) const;
#line 30 "../../../src/options/../main/options"
template <> void Options::assign(options::threadArgv__option_t, std::string option, std::string value, SmtEngine* smt);
#line 32 "../../../src/options/../main/options"
template <> void Options::set(options::thread_id__option_t, const options::thread_id__option_t::type& x);
#line 32 "../../../src/options/../main/options"
template <> const options::thread_id__option_t::type& Options::operator[](options::thread_id__option_t) const;
#line 32 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::thread_id__option_t) const;
#line 32 "../../../src/options/../main/options"
template <> void Options::assign(options::thread_id__option_t, std::string option, std::string value, SmtEngine* smt);
#line 34 "../../../src/options/../main/options"
template <> void Options::set(options::sharingFilterByLength__option_t, const options::sharingFilterByLength__option_t::type& x);
#line 34 "../../../src/options/../main/options"
template <> const options::sharingFilterByLength__option_t::type& Options::operator[](options::sharingFilterByLength__option_t) const;
#line 34 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::sharingFilterByLength__option_t) const;
#line 34 "../../../src/options/../main/options"
template <> void Options::assign(options::sharingFilterByLength__option_t, std::string option, std::string value, SmtEngine* smt);
#line 36 "../../../src/options/../main/options"
template <> const options::fallbackSequential__option_t::type& Options::operator[](options::fallbackSequential__option_t) const;
#line 36 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::fallbackSequential__option_t) const;
#line 36 "../../../src/options/../main/options"
template <> void Options::assignBool(options::fallbackSequential__option_t, std::string option, bool value, SmtEngine* smt);
#line 38 "../../../src/options/../main/options"
template <> const options::incrementalParallel__option_t::type& Options::operator[](options::incrementalParallel__option_t) const;
#line 38 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::incrementalParallel__option_t) const;
#line 38 "../../../src/options/../main/options"
template <> void Options::assignBool(options::incrementalParallel__option_t, std::string option, bool value, SmtEngine* smt);
#line 41 "../../../src/options/../main/options"
template <> const options::segvSpin__option_t::type& Options::operator[](options::segvSpin__option_t) const;
#line 41 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::segvSpin__option_t) const;
#line 41 "../../../src/options/../main/options"
template <> void Options::assignBool(options::segvSpin__option_t, std::string option, bool value, SmtEngine* smt);
#line 45 "../../../src/options/../main/options"
template <> const options::waitToJoin__option_t::type& Options::operator[](options::waitToJoin__option_t) const;
#line 45 "../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::waitToJoin__option_t) const;
#line 45 "../../../src/options/../main/options"
template <> void Options::assignBool(options::waitToJoin__option_t, std::string option, bool value, SmtEngine* smt);

#line 44 "../../../src/options/base_options_template.h"

namespace options {


#line 8 "../../../src/options/../main/options"
inline version__option_t::type version__option_t::operator()() const { return Options::current()[*this]; }
#line 8 "../../../src/options/../main/options"
inline bool version__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 11 "../../../src/options/../main/options"
inline help__option_t::type help__option_t::operator()() const { return Options::current()[*this]; }
#line 11 "../../../src/options/../main/options"
inline bool help__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 22 "../../../src/options/../main/options"
inline earlyExit__option_t::type earlyExit__option_t::operator()() const { return Options::current()[*this]; }
#line 22 "../../../src/options/../main/options"
inline bool earlyExit__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 26 "../../../src/options/../main/options"
inline threads__option_t::type threads__option_t::operator()() const { return Options::current()[*this]; }
#line 26 "../../../src/options/../main/options"
inline bool threads__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 30 "../../../src/options/../main/options"
inline threadArgv__option_t::type threadArgv__option_t::operator()() const { return Options::current()[*this]; }
#line 30 "../../../src/options/../main/options"
inline bool threadArgv__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 30 "../../../src/options/../main/options"
inline void threadArgv__option_t::set(const threadArgv__option_t::type& v) { Options::current().set(*this, v); }

#line 32 "../../../src/options/../main/options"
inline thread_id__option_t::type thread_id__option_t::operator()() const { return Options::current()[*this]; }
#line 32 "../../../src/options/../main/options"
inline bool thread_id__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 32 "../../../src/options/../main/options"
inline void thread_id__option_t::set(const thread_id__option_t::type& v) { Options::current().set(*this, v); }

#line 34 "../../../src/options/../main/options"
inline sharingFilterByLength__option_t::type sharingFilterByLength__option_t::operator()() const { return Options::current()[*this]; }
#line 34 "../../../src/options/../main/options"
inline bool sharingFilterByLength__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 34 "../../../src/options/../main/options"
inline void sharingFilterByLength__option_t::set(const sharingFilterByLength__option_t::type& v) { Options::current().set(*this, v); }

#line 36 "../../../src/options/../main/options"
inline fallbackSequential__option_t::type fallbackSequential__option_t::operator()() const { return Options::current()[*this]; }
#line 36 "../../../src/options/../main/options"
inline bool fallbackSequential__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 38 "../../../src/options/../main/options"
inline incrementalParallel__option_t::type incrementalParallel__option_t::operator()() const { return Options::current()[*this]; }
#line 38 "../../../src/options/../main/options"
inline bool incrementalParallel__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 41 "../../../src/options/../main/options"
inline segvSpin__option_t::type segvSpin__option_t::operator()() const { return Options::current()[*this]; }
#line 41 "../../../src/options/../main/options"
inline bool segvSpin__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 45 "../../../src/options/../main/options"
inline waitToJoin__option_t::type waitToJoin__option_t::operator()() const { return Options::current()[*this]; }
#line 45 "../../../src/options/../main/options"
inline bool waitToJoin__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 50 "../../../src/options/base_options_template.h"

}/* CVC4::options namespace */

}/* CVC4 namespace */

#endif /* __CVC4__OPTIONS__DRIVER_H */
