/*********************                                                        */
/** options_holder.h
 **
 ** Copyright 2011-2013  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     ../../../src/options/mkoptions 
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead:                     */
/*  */

/*********************                                                        */
/*! \file options_holder_template.h
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2013  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Global (command-line, set-option, ...) parameters for SMT
 **
 ** Global (command-line, set-option, ...) parameters for SMT.
 **/

#include "cvc4_private.h"

#ifndef __CVC4__OPTIONS__OPTIONS_HOLDER_H
#define __CVC4__OPTIONS__OPTIONS_HOLDER_H


#line 80 "../../../src/options/base_options"
#include "options/base_options.h"
#line 6 "../../../src/options/../expr/options"
#include "expr/options.h"
#line 6 "../../../src/options/../theory/booleans/options"
#include "theory/booleans/options.h"
#line 6 "../../../src/options/../theory/options"
#include "theory/options.h"
#line 6 "../../../src/options/../theory/bv/options"
#include "theory/bv/options.h"
#line 6 "../../../src/options/../theory/datatypes/options"
#include "theory/datatypes/options.h"
#line 6 "../../../src/options/../theory/builtin/options"
#include "theory/builtin/options.h"
#line 6 "../../../src/options/../theory/arith/options"
#include "theory/arith/options.h"
#line 6 "../../../src/options/../theory/uf/options"
#include "theory/uf/options.h"
#line 6 "../../../src/options/../theory/arrays/options"
#include "theory/arrays/options.h"
#line 6 "../../../src/options/../theory/quantifiers/options"
#include "theory/quantifiers/options.h"
#line 6 "../../../src/options/../theory/rewriterules/options"
#include "theory/rewriterules/options.h"
#line 6 "../../../src/options/../theory/strings/options"
#include "theory/strings/options.h"
#line 6 "../../../src/options/../prop/options"
#include "prop/options.h"
#line 6 "../../../src/options/../proof/options"
#include "proof/options.h"
#line 6 "../../../src/options/../printer/options"
#include "printer/options.h"
#line 6 "../../../src/options/../smt/options"
#include "smt/options.h"
#line 6 "../../../src/options/../decision/options"
#include "decision/options.h"
#line 6 "../../../src/options/../main/options"
#include "main/options.h"
#line 6 "../../../src/options/../parser/options"
#include "parser/options.h"
#line 6 "../../../src/options/../theory/idl/options"
#include "theory/idl/options.h"

#line 25 "../../../src/options/options_holder_template.h"

namespace CVC4 {
namespace options {

struct OptionsHolder {
  OptionsHolder();

  CVC4_OPTIONS__BASE__FOR_OPTION_HOLDER
  CVC4_OPTIONS__EXPR__FOR_OPTION_HOLDER
  CVC4_OPTIONS__BOOLEANS__FOR_OPTION_HOLDER
  CVC4_OPTIONS__THEORY__FOR_OPTION_HOLDER
  CVC4_OPTIONS__BV__FOR_OPTION_HOLDER
  CVC4_OPTIONS__DATATYPES__FOR_OPTION_HOLDER
  CVC4_OPTIONS__BUILTIN__FOR_OPTION_HOLDER
  CVC4_OPTIONS__ARITH__FOR_OPTION_HOLDER
  CVC4_OPTIONS__UF__FOR_OPTION_HOLDER
  CVC4_OPTIONS__ARRAYS__FOR_OPTION_HOLDER
  CVC4_OPTIONS__QUANTIFIERS__FOR_OPTION_HOLDER
  CVC4_OPTIONS__REWRITE_RULES__FOR_OPTION_HOLDER
  CVC4_OPTIONS__STRINGS__FOR_OPTION_HOLDER
  CVC4_OPTIONS__PROP__FOR_OPTION_HOLDER
  CVC4_OPTIONS__PROOF__FOR_OPTION_HOLDER
  CVC4_OPTIONS__PRINTER__FOR_OPTION_HOLDER
  CVC4_OPTIONS__SMT__FOR_OPTION_HOLDER
  CVC4_OPTIONS__DECISION__FOR_OPTION_HOLDER
  CVC4_OPTIONS__DRIVER__FOR_OPTION_HOLDER
  CVC4_OPTIONS__PARSER__FOR_OPTION_HOLDER
  CVC4_OPTIONS__IDL__FOR_OPTION_HOLDER

#line 34 "../../../src/options/options_holder_template.h"

};/* struct OptionsHolder */

}/* CVC4::options namespace */
}/* CVC4 namespace */

#endif /* __CVC4__OPTIONS__OPTIONS_HOLDER_H */
