/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ../../../../src/parser/smt2/Smt2.g
 *     -                            On : 2013-12-06 18:07:53
 *     -                for the parser : Smt2ParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
Smt2Parser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pSmt2Parser, which is returned from a call to Smt2ParserNew().
 *
 * The methods in pSmt2Parser are  as follows:
 *
 *  - 
 CVC4::parser::smt2::myExpr
      pSmt2Parser->parseExpr(pSmt2Parser)
 *  - 
 CVC4::Command*
      pSmt2Parser->parseCommand(pSmt2Parser)
 *  - 
 CVC4::Command*
      pSmt2Parser->command(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->extendedCommand(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->rewriterulesCommand(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->rewritePropaKind(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->pattern(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->simpleSymbolicExprNoKeyword(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->keyword(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->simpleSymbolicExpr(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->symbolicExpr(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->term(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->attribute(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->indexedFunctionName(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->badIndexedFunctionName(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->termList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->str(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->builtinOp(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->quantOp(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->functionName(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->functionSymbol(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->sortList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->nonemptySortList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->sortedVarList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->sortName(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->sortSymbol(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->symbolList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->symbol(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->nonemptyNumeralList(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->datatypeDef(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->constructorDef(pSmt2Parser)
 *  - 
 void
      pSmt2Parser->selector(pSmt2Parser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_Smt2Parser_H
#define _Smt2Parser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#include "expr/command.h"
#include "parser/parser.h"
#include "parser/antlr_tracing.h"

namespace CVC4 {
  class Expr;

  namespace parser {
    namespace smt2 {
      /**
       * Just exists to provide the uintptr_t constructor that ANTLR
       * requires.
       */
      struct myExpr : public CVC4::Expr {
        myExpr() : CVC4::Expr() {}
        myExpr(void*) : CVC4::Expr() {}
        myExpr(const Expr& e) : CVC4::Expr(e) {}
        myExpr(const myExpr& e) : CVC4::Expr(e) {}
      };/* struct myExpr */
    }/* CVC4::parser::smt2 namespace */
  }/* CVC4::parser namespace */
}/* CVC4 namespace */



#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct Smt2Parser_Ctx_struct Smt2Parser, * pSmt2Parser;



/**
 ** This file is part of CVC4.
 ** Copyright (c) 2009-2013  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.
 **/


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
Smt2Parser

 */
struct Smt2Parser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     CVC4::parser::smt2::myExpr
     (*parseExpr)	(struct Smt2Parser_Ctx_struct * ctx);

     CVC4::Command*
     (*parseCommand)	(struct Smt2Parser_Ctx_struct * ctx);

     CVC4::Command*
     (*command)	(struct Smt2Parser_Ctx_struct * ctx);

     void
     (*extendedCommand)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Command*& cmd);

     void
     (*rewriterulesCommand)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Command*& cmd);

     void
     (*rewritePropaKind)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Kind& kind);

     void
     (*pattern)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Expr& expr);

     void
     (*simpleSymbolicExprNoKeyword)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::SExpr& sexpr);

     void
     (*keyword)	(struct Smt2Parser_Ctx_struct * ctx, std::string& s);

     void
     (*simpleSymbolicExpr)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::SExpr& sexpr);

     void
     (*symbolicExpr)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::SExpr& sexpr);

     void
     (*term)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Expr& expr, CVC4::Expr& expr2);

     void
     (*attribute)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Expr& expr, CVC4::Expr& retExpr, std::string& attr);

     void
     (*indexedFunctionName)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Expr& op);

     void
     (*badIndexedFunctionName)	(struct Smt2Parser_Ctx_struct * ctx);

     void
     (*termList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<CVC4::Expr>& formulas, CVC4::Expr& expr);

     void
     (*str)	(struct Smt2Parser_Ctx_struct * ctx, std::string& s);

     void
     (*builtinOp)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Kind& kind);

     void
     (*quantOp)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Kind& kind);

     void
     (*functionName)	(struct Smt2Parser_Ctx_struct * ctx, std::string& name, CVC4::parser::DeclarationCheck check);

     void
     (*functionSymbol)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Expr& fun);

     void
     (*sortList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<CVC4::Type>& sorts);

     void
     (*nonemptySortList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<CVC4::Type>& sorts);

     void
     (*sortedVarList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<std::pair<std::string, CVC4::Type> >& sortedVars);

     void
     (*sortName)	(struct Smt2Parser_Ctx_struct * ctx, std::string& name, CVC4::parser::DeclarationCheck check);

     void
     (*sortSymbol)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Type& t, CVC4::parser::DeclarationCheck check);

     void
     (*symbolList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<std::string>& names, CVC4::parser::DeclarationCheck check, CVC4::parser::SymbolType type);

     void
     (*symbol)	(struct Smt2Parser_Ctx_struct * ctx, std::string& id, CVC4::parser::DeclarationCheck check, CVC4::parser::SymbolType type);

     void
     (*nonemptyNumeralList)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<uint64_t>& numerals);

     void
     (*datatypeDef)	(struct Smt2Parser_Ctx_struct * ctx, std::vector<CVC4::Datatype>& datatypes, std::vector< CVC4::Type >& params);

     void
     (*constructorDef)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::Datatype& type);

     void
     (*selector)	(struct Smt2Parser_Ctx_struct * ctx, CVC4::DatatypeConstructor& ctor);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct Smt2Parser_Ctx_struct * ctx);
    void	    (*free)   (struct Smt2Parser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pSmt2Parser Smt2ParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pSmt2Parser Smt2ParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__136      136
#define T__137      137
#define T__138      138
#define T__139      139
#define T__140      140
#define T__141      141
#define ABS_TOK      4
#define ALPHA      5
#define AMPERSAND_TOK      6
#define AND_TOK      7
#define ASSERT_TOK      8
#define AS_TOK      9
#define ATTRIBUTE_NAMED_TOK      10
#define ATTRIBUTE_NO_PATTERN_TOK      11
#define ATTRIBUTE_PATTERN_TOK      12
#define ATTRIBUTE_TOK      13
#define AT_TOK      14
#define BINARY_LITERAL      15
#define BV2NAT_TOK      16
#define BVADD_TOK      17
#define BVAND_TOK      18
#define BVASHR_TOK      19
#define BVCOMP_TOK      20
#define BVLSHR_TOK      21
#define BVMUL_TOK      22
#define BVNAND_TOK      23
#define BVNEG_TOK      24
#define BVNOR_TOK      25
#define BVNOT_TOK      26
#define BVOR_TOK      27
#define BVSDIV_TOK      28
#define BVSGE_TOK      29
#define BVSGT_TOK      30
#define BVSHL_TOK      31
#define BVSLE_TOK      32
#define BVSLT_TOK      33
#define BVSMOD_TOK      34
#define BVSREM_TOK      35
#define BVSUB_TOK      36
#define BVUDIV_TOK      37
#define BVUGE_TOK      38
#define BVUGT_TOK      39
#define BVULE_TOK      40
#define BVULT_TOK      41
#define BVUREM_TOK      42
#define BVXNOR_TOK      43
#define BVXOR_TOK      44
#define CHECKSAT_TOK      45
#define COMMENT      46
#define CONCAT_TOK      47
#define DECIMAL_LITERAL      48
#define DECLARE_CONST_TOK      49
#define DECLARE_DATATYPES_TOK      50
#define DECLARE_FUNS_TOK      51
#define DECLARE_FUN_TOK      52
#define DECLARE_PREDS_TOK      53
#define DECLARE_SORTS_TOK      54
#define DECLARE_SORT_TOK      55
#define DEFINE_FUN_TOK      56
#define DEFINE_SORT_TOK      57
#define DEFINE_TOK      58
#define DIGIT      59
#define DISTINCT_TOK      60
#define DIVISIBLE_TOK      61
#define DIV_TOK      62
#define ECHO_TOK      63
#define EQUAL_TOK      64
#define ESCAPE      65
#define EXISTS_TOK      66
#define EXIT_TOK      67
#define FORALL_TOK      68
#define GET_ASSERTIONS_TOK      69
#define GET_ASSIGNMENT_TOK      70
#define GET_INFO_TOK      71
#define GET_MODEL_TOK      72
#define GET_OPTION_TOK      73
#define GET_PROOF_TOK      74
#define GET_UNSAT_CORE_TOK      75
#define GET_VALUE_TOK      76
#define GREATER_THAN_EQUAL_TOK      77
#define GREATER_THAN_TOK      78
#define HEX_DIGIT      79
#define HEX_LITERAL      80
#define IMPLIES_TOK      81
#define INCLUDE_TOK      82
#define INDEX_TOK      83
#define INT2BV_TOK      84
#define INTEGER_LITERAL      85
#define INTS_DIV_TOK      86
#define INTS_MOD_TOK      87
#define IS_INT_TOK      88
#define ITE_TOK      89
#define KEYWORD      90
#define LESS_THAN_EQUAL_TOK      91
#define LESS_THAN_TOK      92
#define LET_TOK      93
#define LPAREN_TOK      94
#define MINUS_TOK      95
#define NOT_TOK      96
#define NUMERAL      97
#define OR_TOK      98
#define PLUS_TOK      99
#define POP_TOK      100
#define POUND_TOK      101
#define PROPAGATION_RULE_TOK      102
#define PUSH_TOK      103
#define QUOTED_SYMBOL      104
#define RECON_TOK      105
#define REDUCTION_RULE_TOK      106
#define REINTER_TOK      107
#define REOPT_TOK      108
#define REOR_TOK      109
#define REPLUS_TOK      110
#define RERANGE_TOK      111
#define RESTAR_TOK      112
#define REWRITE_RULE_TOK      113
#define RPAREN_TOK      114
#define SELECT_TOK      115
#define SET_INFO_TOK      116
#define SET_LOGIC_TOK      117
#define SET_OPTION_TOK      118
#define SIMPLE_SYMBOL      119
#define SIMPLIFY_TOK      120
#define STAR_TOK      121
#define STORE_TOK      122
#define STRCON_TOK      123
#define STRING_LITERAL      124
#define STRINRE_TOK      125
#define STRLEN_TOK      126
#define STRSUB_TOK      127
#define STRTORE_TOK      128
#define SYMBOL_CHAR      129
#define SYMBOL_CHAR_NOUNDERSCORE_NOATTRIBUTE      130
#define TO_INT_TOK      131
#define TO_REAL_TOK      132
#define UNTERMINATED_QUOTED_SYMBOL      133
#define WHITESPACE      134
#define XOR_TOK      135
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for Smt2Parser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
